title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Learning Graphs for Knowledge Transfer with Limited Labels
description: |+
             Pallabi Ghosh,        Nirat Saini,        Larry S. Davis,        Abhinav Shrivastava 
description: University of Maryland
