theme: jekyll-theme-cayman
title: Learning Graphs for Knowledge Transfer with Limited Labels
description: ' Pallabi Ghosh,        Nirat Saini,        Larry S. Davis,        Abhinav Shrivastava \n University of Maryland'
